---
- name: macOS bootstrap
  hosts: localhost
  connection: local
  become: false

  vars:
    brew_packages:
      - neovim
      - antidote
      - starship
      - chezmoi
      - pyenv
      - uv
      - nvm
      - rustup
      - httpie
      - mintoolkit
      - eza
      - bat
      - doctl
      - cloudflare-cli4
      - awscli
      - pass
      - kubernetes-cli
      - k9s
      - helm
      - kind
      - just
      - ripgrep
      - the_silver_searcher
      - mongosh
      - mongodb-database-tools
      - pulumi
      - claude-code
      - opentofu
      # fonts
      - font-fira-code-nerd-font
      - k6

    brew_cask_packages:
      - zed
      - swish
      - protonvpn
      - proton-mail-bridge
      - little-snitch
      - bitwarden
      - proxyman
      - karabiner-elements
      - wezterm
      - claude
      - orbstack
      - syncthing
      - discord
      - elgato-wave-link
      - elgato-stream-deck
      - elgato-camera-hub
      - obsidian
      - notion
      - vlc
      - mongodb-compass
      - lens
      - beekeeper-studio
      - tidal
      - firefox@developer-edition

  tasks:
    - name: Update Homebrew
      command: brew update

    - homebrew_tap:
        name: mongodb/brew
        state: present

    - name: Install Homebrew packages
      homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ brew_packages }}"

    - name: Install Homebrew cask packages
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop: "{{ brew_cask_packages }}"
